
global_frame: map
robot_base_frame: base_footprint
# update_frequency: 2.0
update_frequency: 2.0
publish_frequency: 1.0
static_map: false
rolling_window: true
width: 10.0
height: 10.0
resolution: 0.05
transform_tolerance: 0.5

plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
  observation_sources: scan
  scan: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

inflation_layer:
  inflation_radius: 0.05
