base_global_planner: "navfn/NavfnROS"
base_local_planner: "base_local_planner/TrajectoryPlannerROS"
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 3.0
transform_tolerance: 0.5
recovery_behavior_enabled: true
clearing_rotation_allowed: true
shutdown_costmaps: false
oscillation_timeout: 10.0
oscillation_distance: 0.5
NavfnROS:
  allow_unknown: true   # 如果地圖中有未知空白格，這個要設 true